<%-- 
    Document   : show_table
    Created on : 2015-5-25, 13:18:32
    Author     : apple
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="./image/analysis.jpg">

        <title>Programmer Assistor</title>

        <!-- Bootstrap core CSS -->
        <link href="./css/bootstrap.min.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="./js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Custom styles for this template -->
        <link href="./css/show.css" rel="stylesheet">
    </head>
    <!-- NAVBAR
    ================================================== -->
    <body>
        <div class="navbar-wrapper">
            <div class="container">
                <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Programmer Assistor</a>
                        </div>
                        <div id="navbar" class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="home.html">Home </a></li>
                                <li><a href="#about">Help </a></li>
                                <li><a href="#contact">About </a></li>
                                <li class="active"><a href="show.html">Show </a></li>

                            </ul>
                        </div>
                    </div>
                </nav>

            </div>
        </div>
        <!-- Marketing messaging and featurettes
           ================================================== -->
        <!-- Wrap the rest of the page in another container to center all the content. -->

        <div class="container marketing">

            <!-- START THE FEATURETTES -->

            <div class="row featurette show_divider">

                <form action="GenerateViewServlet" method="POST">
                    <div class="form-group">
                        <h3>Please input reletive path of file that generated by MALLET.</h3>
                        <br/>
                    </div>
                    <div class="form-group">
                        <label for="topicKeys">--output-topic-keys:</label>
                        <input type="text" class="form-control" name="topicKeys" id="topicKeys" 
                               placeholder="File path for --output-topic-keys" required="" 
                               value="<%= request.getParameter("topicKeys")%>">
                    </div>
                    <div class="form-group">
                        <label for="wordCounts">--word-topic-counts-file:</label>
                        <input type="text" class="form-control" name="wordCounts" id="wordCounts" 
                               placeholder="File path for --word-topic-counts-file" required="" 
                               value="<%= request.getParameter("wordCounts")%>">
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-8">
                                <label for="viewStyle">View Style:</label>
                                <select class="form-control" name="viewStyle" id="viewStyle">
                                    <option selected="">Table</option>
                                    <option>Topics Frequency</option>
                                    <option>Bubble Chart</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <p class="help-block illustrate">
                        After clicking the button, you can see generated topics in different styles. And you can change style by selecting in the dropdwon list.
                    </p>
                    <br/>
                    <input type="submit" class="btn btn-primary processButton" value="Start Showing" />
                    <!--<button type="submit" class="btn btn-primary processButton">Start Showing</button>-->
                </form>
            </div>

            <hr class="featurette-divider">

            <!-- /END THE FEATURETTES -->


            <!-- FOOTER -->
            <footer>
                <p class="pull-right"><a href="#">Back to top</a></p>
                <p>2015 @Tianxia, Wang</p>
            </footer>

        </div><!-- /.container -->


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="./js/jquery.min.js"></script>
        <script src="./js/bootstrap.min.js"></script>
        <script src="./js/docs.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="./js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>
