<%-- 
    Document   : style_bubble
    Created on : 2015-5-24, 17:36:09
    Author     : apple
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="./image/analysis.jpg">

        <title>Programmer Assistor</title>

        <!-- Bootstrap core CSS -->
        <link href="./css/bootstrap.min.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="./js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Custom styles for this template -->
        <link href="./css/show.css" rel="stylesheet">
    </head>
    <body>
        <div class="navbar-wrapper">
            <div class="container">
                <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">Programmer Assistor</a>
                        </div>
                        <div id="navbar" class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a href="home.html">Home </a></li>
                                <li><a href="help.html">Help </a></li>
                                <li><a href="about">About </a></li>
                                
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Styles <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="show_table.jsp?topicKeys=<%= request.getParameter("topicKeys")%>&wordCounts=<%= request.getParameter("wordCounts")%>">Table</a></li>
                                        <li><a href="show_frequency.jsp?topicKeys=<%= request.getParameter("topicKeys")%>&wordCounts=<%= request.getParameter("wordCounts")%>">Topics Frequency</a></li>                                        
                                        <li><a href="#">Bubble Chart</a></li>
                                    </ul>
                                </li>

                            </ul>
                        </div>
                    </div>
                </nav>

            </div>
        </div>
        <!-- Marketing messaging and featurettes
           ================================================== -->
        <!-- Wrap the rest of the page in another container to center all the content. -->

        <div class="container marketing">
            <div class="row featurette show_divider">
                <h4>Your input path of file that generated by MALLET:</h4>
                <p>--output-topic-keys: <%=request.getParameter("topicKeys")%></p>
                <p>--word-topic-counts-file: <%=request.getParameter("wordCounts")%></p>
                <p class="illustrate">If you want to input again, please click <a href="show.html">here</a></p>
                <br/>
                <h3>Bubble Chart:</h3>
            </div>

        </div><!-- /.container -->

        <!-- Bootstrap core JavaScript
================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="./js/jquery.min.js"></script>
        <script src="./js/bootstrap.min.js"></script>
        <script src="./js/docs.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="./js/ie10-viewport-bug-workaround.js"></script>
        <!--custom js -->
        <script src="./js/home.js"></script>
        <script src="./js/d3.v3.min.js"></script>
        <script>

            var diameter = 960,
                    format = d3.format(",d"),
                    color = d3.scale.category20c();

            var bubble = d3.layout.pack()
                    .sort(null)
                    .size([diameter, diameter])
                    .padding(1.5);

            var svg = d3.select("body").append("svg")
                    .attr("width", diameter)
                    .attr("height", diameter)
                    .attr("class", "bubble");

            d3.json("topics.json", function(error, root) {
                var node = svg.selectAll(".node")
                        .data(bubble.nodes(classes(root))
                                .filter(function(d) {
                                    return !d.children;
                                }))
                        .enter().append("g")
                        .attr("class", "node")
                        .attr("transform", function(d) {
                            return "translate(" + d.x + "," + d.y + ")";
                        });

                node.append("title")
                        .text(function(d) {
                            return d.className + ": " + format(d.value);
                        });

                node.append("circle")
                        .attr("r", function(d) {
                            return d.r;
                        })
                        .style("fill", function(d) {
                            return color(d.packageName);
                        });

                node.append("text")
                        .attr("dy", ".3em")
                        .style("text-anchor", "middle")
                        //      .text(function(d) { return d.className.substring(0, d.r / 3); });
                        .text(function(d) {
                            return d.className.substring(0, d.r * 2 / 5);
                        });
            });

            // Returns a flattened hierarchy containing all leaf nodes under the root.
            function classes(root) {
                var classes = [];

                function recurse(name, node) {
                    if (node.children)
                        node.children.forEach(function(child) {
                            recurse(node.name, child);
                        });
                    else
                        classes.push({packageName: name, className: node.name, value: node.size});
                }

                recurse(null, root);
                return {children: classes};
            }

            d3.select(self.frameElement).style("height", diameter + "px");

        </script>
    </body>
</html>